### ISSUE TITLE
neat skype still calls when empathizers are 'do not disturb' or 'invisible'

### ISSUE THREAD

**Issue by Peijman** [EmpathyApp/EmpathyApp#77] opened 2015-02-12 21:16 UTC
when empathizer puts "do not disturb" or "invisible" - neat skype still calls them? shows as offline status on the page, but when you click it still calls. --- neat skype status says that you have the option to change this.. maybe you can change this in the code editor of the plugin in wordpress?  If it is online or away then calling is what we want. Basically if it is do not disturb or invisible, then chatting is what we want to happen. If it is offline, then no action should be taken. 
Any ideas on how to do this?

**Comment by SunyataZero** [comment] 2015-02-12 21:19
i can look into this issue. worst-case scenario: we may need to change
skype for something else (this is not as big of a deal as it sounds since
none of our own code actually interacts with neat skype status)

On Thu, Feb 12, 2015 at 10:16 PM, Peijman <notifications@github.com> wrote:

> when empathizer puts "do not disturb" or "invisible" - neat skype still
> calls them? shows as offline status on the page, but when you click it
> still calls. --- neat skype status says that you have the option to change
> this.. maybe you can change this in the code editor of the plugin in
> wordpress? If it is online or away then calling is what we want. Basically
> if it is do not disturb or invisible, then chatting is what we want to
> happen. If it is offline, then no action should be taken.
> Any ideas on how to do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/77>.
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by SunyataZero** [comment] 2015-02-13 14:05
I'm closing this issue since it's a duplicate of #81 (which was resolved when updating the documentation)

**Closed by SunyataZero** 2015-02-13 14:05 UTC
Labels: _priority

**Comment by SunyataZero** [comment] 2015-02-13 14:07
@Peijman Have closed this but i'm now adding emphasis in the documentation to draw attention to this problem, see the bottom of this list: https://github.com/EmpathyApp/EmpathyApp/blob/master/docs/dependencies/risks-and-defects.md
